export const horseNames = [
  "Thunder Bolt",
  "Silver Storm",
  "Midnight Star",
  "Golden Arrow",
  "Wild Spirit",
  "Royal Flash",
  "Dark Knight",
  "Lucky Charm",
  "Swift Wind",
  "Blazing Sun",
  "Moon Shadow",
  "Desert Rose",
  "Mountain Echo",
  "Ocean Wave",
  "Forest Fire",
  "Valley Breeze",
  "Storm Runner",
  "Cloud Dancer",
  "River Song",
  "Dawn Treader",
];

export const colors = [
  "Bay",
  "Chestnut",
  "Black",
  "Grey",
  "Palomino",
  "Buckskin",
  "Roan",
  "Dun",
  "Cremello",
  "Perlino",
  "Sorrel",
  "White",
  "Brown",
  "Liver Chestnut",
  "Dark Bay",
  "Seal Brown",
  "Smoky Black",
  "Red Dun",
  "Grullo",
  "Champagne",
];

export const roundDistances = [1200, 1400, 1600, 1800, 2000, 2200];
